'use client'

import { Footer } from "./Components/Footer";
import { Header } from "./Components/Header";
import { Roboto } from "next/font/google";
import "./globals.css";
import cn from "classnames";
import styles from "./page.module.scss";
import { Provider } from "react-redux";
import { store } from "@/store/store";

export const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const cx = cn.bind(styles);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const className = cx("main", styles.main);

  return (
    <html lang="ru">
      <Provider store={store}>
        <body className={roboto.className}>
          <Header />
          <div className={className}>{children}</div>
          <Footer />
        </body>
      </Provider>
    </html>
  );
}
